### ISSUE TITLE
merge it into vits, but got poor results

### ISSUE THREAD

**Issue by GuangChen2016** [azraelkuan/repgan#5] opened 2023-03-22 15:09 UTC
Hi, I tried to merge it into vits, but got u nrecognizable voices. Did you tried to merge it for end2end training?
Thanks

**Comment by azraelkuan** [comment] 2023-03-23 01:53
yes, i have merged, can u share your samples?

**Comment by GuangChen2016** [comment] 2023-03-23 02:11
![image](https://user-images.githubusercontent.com/23181283/227081183-cb116683-3b3e-4ed3-b0f4-aaded8291184.png)
I got all noise vioice, did you use weightnorm for repgan？

**Comment by azraelkuan** [comment] 2023-03-23 02:13
i think this is not the problem of WN, can u check your training samples but not inference samples?

**Comment by GuangChen2016** [comment] 2023-03-23 02:21
The training sample has similar issues, I have called convert_weight_bias during inference. Is there anything else to be modified?

**Comment by azraelkuan** [comment] 2023-03-23 02:23
the training is almost the same with vits's vocoder model, that should be no problem.
u do not need to call convert_weight_bias  and make sure that the training samples is good

**Comment by GuangChen2016** [comment] 2023-03-23 02:42
Yech, the gererated training samples using forward mode are normal, but  when I called convert_weight_bias and used it for inference mode, the generated samples are all noises.

**Comment by azraelkuan** [comment] 2023-03-23 02:43
check the test code:   https://github.com/azraelkuan/repgan/blob/26323d2ff3dfe80bc660830eb33bcde237343330/repgan.py#L181

**Comment by GuangChen2016** [comment] 2023-03-23 06:46
Thanks. I found that if I inference using the train mode first and then called convert_weight_bias using the eval mode,  I can generate normal results. If I directly called convert_weight_bias using the eval mode, then the results are bad. Do you know the reason?

**Comment by azraelkuan** [comment] 2023-03-23 06:50
may be caused by weight norm， can u try remove weight norm first and then evaluate

**Comment by GuangChen2016** [comment] 2023-04-03 03:54
@azraelkuan Thanks a lot.
Anyther question is that what' s your configuration for multi stft discriminator? I directly used the structure and default configuration of univet, but the results were not that good than msd.
Thanks again.

**Closed as completed** 2024-03-25 12:00 UTC
